services:
  - type: web
    name: library-web
    env: python
    region: oregon
    repo: https://github.com/cw-HX/Library-Project
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn library_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        value: ""
      - key: DEBUG
        value: "false"
      - key: MONGODB_URI
        value: ""
      - key: DATABASE_URL
        value: ""
    autoDeploy: true